export const GET_SESSION_SUCCESS = "GET_SESSION_SUCCESS";
export const GET_POSTS_SUCCESS = "GET_POST_SUCCESS";
export const GET_POSTS_BY_ID_SUCCESS = "GET_POSTS_BY_ID_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS"